---
- name: Check if docker exists
  shell: which docker
  register: docker_exists
  ignore_errors: true

- name: Install Docker
  shell: curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
  when: docker_exists.rc != 0

- name: Create docker compose Systemd unit
  copy: 
    src: docker-compose@.service 
    dest: /etc/systemd/system/docker-compose@.service

- name: Create a directory for symlinks
  file:
    path: /etc/docker/compose
    state: directory

- name: Reload systemd
  shell: systemctl daemon-reload
